[bug]
color = "d73a4a"
name = "bug"
description = "Something isn't working"

[documentation]
color = "1bc4a5"
name = "documentation"
description = "Improvements or additions to documentation"

[duplicate]
color = "cfd3d7"
name = "duplicate"
description = "This issue or pull request already exists"

[enhancement]
color = "a2eeef"
name = "enhancement"
description = "New feature or request"

["good first issue"]
color = "7057ff"
name = "good first issue"
description = "Good for newcomers"

["help wanted"]
color = "008672"
name = "help wanted"
description = "Extra attention is needed"

[question]
color = "d876e3"
name = "question"
description = "Further information is requested"

[removed]
color = "e99695"
name = "removed"
description = "Removed piece of functionalities."

[tests]
color = "bfd4f2"
name = "tests"
description = "CI, CD and testing related changes"

[notplanned]
color = "ffffff"
name = "wontfix"
description = "This will not be worked on"

[planned]
color= "0366d6"
name="planned"
description = "This will be added in a future release"

[discussion]
color = "c2e0c6"
name = "discussion"
description = "Some discussion around the project"

[answered]
color = "0ee2b6"
name = "answered"
description = "Automatically closes as answered after a delay"
