# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: update-services-yaml
        stages: [pre-commit]
        types: [python]
        name: Update services.yaml
        entry: python ./update-services-yaml.py
        language: system
        pass_filenames: false
        always_run: true
  - repo: local
    hooks:
      - id: update-requirements
        stages: [pre-commit]
        types: [python]
        name: Update References to Requirements
        entry: ./update-requirements.py
        language: python
        additional_dependencies:
          - "requirements-parser==0.5.0"
          - "setuptools==69.2.0"
        pass_filenames: false
        always_run: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      #- id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
        exclude: ^.vscode/
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.7
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: local
    hooks:
      - id: pytest-check
        stages: [pre-push]
        types: [python]
        name: pytest-check
        entry: python -m pytest -v tests/
        language: system
        pass_filenames: false
        always_run: true
ci:
  skip:
    - update-services-yaml
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks
    for more information, see https://pre-commit.ci
    [dependabot skip]
