%YAML 1.1
---
send_key:
  name: Send Key
  description: Send a key to the receiver
  target:
    entity:
      integration: magentatv
  fields:
    key_code:
      name: Key Code
      description: Key sent to the receiver
      required: true
      advanced: false
      example: PAUSE
      default: PAUSE
      selector:
        select:
          options:
            - "BACK"
            - "ENTER"
            - "SPACE"
            - "PGUP"
            - "PGDOWN"
            - "LEFT"
            - "UP"
            - "RIGHT"
            - "DOWN"
            - "DELETE"
            - "NUM0"
            - "NUM1"
            - "NUM2"
            - "NUM3"
            - "NUM4"
            - "NUM5"
            - "NUM6"
            - "NUM7"
            - "NUM8"
            - "NUM9"
            - "POUND"
            - "STAR"
            - "F1"
            - "F2"
            - "F3"
            - "F4"
            - "F5"
            - "F6"
            - "F7"
            - "F8"
            - "F9"
            - "F10"
            - "F11"
            - "F12"
            - "F13"
            - "F14"
            - "F15"
            - "F16"
            - "IPTV"
            - "PC"
            - "SOURCE"
            - "PIP"
            - "POWER"
            - "CHANNEL_UP"
            - "CHANNEL_DOWN"
            - "VOL_UP"
            - "VOL_DOWN"
            - "MUTE"
            - "TRACK"
            - "NEXTCH"
            - "FAST_FORWARD"
            - "FAST_REWIND"
            - "END"
            - "BEGIN"
            - "INFO"
            - "INTER"
            - "STOP"
            - "PORTAL"
            - "EPG"
            - "RED"
            - "GREEN"
            - "YELLOW"
            - "BLUE"
            - "SWITCH"
            - "FAV"
            - "HELP"
            - "SETTINGS"
            - "SUBTITLE"
            - "SEARCH"
            - "TVMENU"
            - "VODMENU"
            - "TVODMENU"
            - "NVODMENU"
            - "REPLAY"
            - "SKIP"
            - "EXIT"
            - "LASTCH"
            - "RECORDINGS"
            - "OPTION"
            - "PVR"
            - "RADIO"
            - "ON"
            - "OFF"
            - "DVB_TXT"
            - "MULTIVIEW"
send_text:
  name: Send Text
  description: Send Text to the receiver
  target:
    entity:
      integration: magentatv
  fields:
    text:
      name: Text
      description: Text send to the receiver
      required: true
      advanced: false
      example: Awaken your home
      default: Anything
      selector:
        text:
