# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.magentatv: debug
    #async_upnp_client.traffic.upnp: debug
#    async_upnp_client: debug
debugpy:
#ssdp:
magentatv:
  ports: 1200 - 1400