# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    ssdp: debug
    homeassistant.components.ssdp: debug
    custom_components.magentatv: debug
debugpy:
ssdp: