name: "Lint"

on:
  push:
    branches:
      - "main"
      - "feature/*"
  pull_request:
    branches:
      - "main"

jobs:
  ruff:
    name: "Ruff"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@v5.0.0"

        - name: "Set up Python"
          uses: actions/setup-python@v6.0.0
          with:
            python-version: "3.13"
            cache: "pip"

        - name: "Install requirements"
          run: pip install -r requirements-dev.txt

        - name: "Lint"
          run: ruff check --output-format=github .
