name: "Test"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  Test:
    name: "Pytest"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@v3.5.2"

        - name: "Set up Python"
          uses: actions/setup-python@v4.6.1
          with:
            python-version: "3.10"
            cache: "pip"

        - name: "Install requirements"
          run: pip install -r requirements-dev.txt

        - name: "Test"
          run: pytest tests --doctest-modules --junitxml=pytest.xml --cov --cov-report=xml --cov-report=term-missing

        - name: Pytest coverage comment
          if: ${{ github.event_name == 'pull_request' }}
          uses: MishaKav/pytest-coverage-comment@main
          with:
            pytest-xml-coverage-path: ./coverage.xml
            junitxml-path: ./pytest.xml
